name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # è·å–æ‰€æœ‰å†å²ï¼Œä»¥ä¾¿èƒ½å¤Ÿè®¿é—®æœ€æ–°çš„æäº¤ä¿¡æ¯

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install and Build ğŸ”§
        run: |
          npm install
          npm run build

      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_KEY }}

      # - name: Clone Private Repository via SSH
      #   run: |
      #     git clone git@github.com:jue/bimgo-api.git
      #     mkdir -p bimgo-api/app/public
      #     rm -rf bimgo-api/app/public/*

      #     echo "Copying files from dist to bimgo-api/public"
      #     cp -r dist/* bimgo-api/app/public/
      #     cd bimgo-api

      #     git config user.email "i@xiangjianfeng.com"
      #     git config user.name "jue"

      #     echo "Adding changes to git..."
      #     git add app/public/

      # - name: Get commit message
      #   id: get_commit_message
      #   run: |
      #     COMMIT_MSG=$(git log -1 --pretty=format:%s)
      #     echo "::set-output name=message::$COMMIT_MSG"

      # - name: Deploy
      #   run: |
      #     cd bimgo-api
      #     echo "Attempting to commit changes..."
      #     git commit -m "${{ steps.get_commit_message.outputs.message }}" || echo "No changes to commit."
      #     echo "Pushing changes..."
      #     git push

      # - name: Deploy to Server
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #       SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #       ARGS: "-rltgoDzvO --delete"
      #       SOURCE: "dist/"
      #       REMOTE_HOST: "47.116.193.226"
      #       REMOTE_USER: "root"
      #       TARGET: "/www/wwwroot/tcas/public"

#       - name: Install coscmd
#         run: sudo pip install coscmd

#       - name: Configure coscmd
#         env:
#           SECRET_ID: ${{ secrets.SecretId }}
#           SECRET_KEY: ${{ secrets.SecretKey }}
#           BUCKET: bufengren-1253454329
#           REGION: ap-shanghai
#         run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

#       - name: Upload
#         run: cd ./dist && coscmd upload -rs --delete -f ./ /
